version: '3.8'
services:

  mongodb:
    image: mongo:4.4.15
    container_name: mongodb-sample-analytics
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=haininhgl
      - MONGO_INITDB_ROOT_PASSWORD=haininhgl
    volumes:
      - mongodb:/var/lib/db/data/
    networks:
      mss-dev:
        aliases:
          - mongodb

networks:
  mss-dev:
    name: mss-dev

volumes:
  mongodb:
